### ISSUE TITLE
Syntax explanation of mal12 and malx

### ISSUE THREAD

**Issue by CleverLemming1337** [HeyTomCat/ProgramLangs#1]
@HeyTomCat Maybe you could add an explanation of mal12‘s and malx‘ syntax? Maybe you could do this in the wiki.

**Comment by CleverLemming1337** [comment]
Sorry, I didn't see the cmd.txt file.

**Comment by HeyTomCat** [comment]
MAL12 is discontinued, so you'll have to work with mal12_cmd.txt. But for MALX i created a specification (see spec.md).
